spring:
  datasource:
    url: jdbc:mysql://database-1.cqrf0f1mttmf.us-east-1.rds.amazonaws.com:3306/hr
    username: admin
    password: admin1234
#    url: jdbc:h2:mem:testDB
#    username: sa
#    password: sa
#  h2:
#    console:
#      path: /h2
#      enabled: true
#      settings:
#        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true        
server:
  port: 5000
  