spring:
  datasource:
    url: jdbc:mysql://3.92.251.22:3307/hr
    username: root
    password: root
#    url: jdbc:h2:mem:testDB
#    username: sa
#    password: sa
#  h2:
#    console:
#      path: /h2
#      enabled: true
#      settings:
#        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true        
  application:
    name: employee-app
server:
  port: 5000
  